#ifndef USERTOOLSTATE_H
#define USERTOOLSTATE_H

enum UserToolState{
    SELECT_POINT,
    SELECT_POINT_ISLAND,
    SELECT_EDGE,
    SELECT_BORDER_EDGES,
    SELECT_TRIANGLE,
    SELECT_QUAD,
    SELECT_MODE, //???
    MANIP_TRANSLATE,
    MANIP_ROTATE,
    MANIP_SCALE,
    ADD_POINT,
    ADD_POINT_CHAIN,
    MOVE_POINT,
    ADD_EDGE,
    EXTRUDE_EDGE,
    DIVIDE_EDGE,
    DIVIDE_TRIANGLE,
    CYLINDER_PROJECTION,
    CONSTRAINT_PROJECTION
};

#endif // USERTOOLSTATE_H
